# Generated by Django 5.0.6 on 2024-06-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='tbl_students',
        ),
    ]
