# Generated by Django 5.0.6 on 2024-06-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='confrim_password',
            new_name='con_password',
        ),
    ]
