# Generated by Django 5.0.6 on 2024-06-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_confrim_password_stud_con_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='con_password',
            new_name='confrim_password',
        ),
    ]
